### ISSUE TITLE
conditional settings

### ISSUE THREAD

**Issue by ModProg** [dnaka91/cargo-hatch#10]
add a condition similarly to the file ignores to arguments to allow only querying some options when an earlier prompt was answered with yes.

```toml
[bin_install]
type = "bool"
description = "Enable binary installer (requires releases on GitHub)"
default = true

[github_repo]
type = "string"
description = "Enable binary installer (requires releases on GitHub)"
condition = "{{ bin_install }}"
```
should only ask for `github_repo` if `bin_install` is answered with yes.
